# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=140)),
                ('messages', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
