# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
